from datetime import timedelta

GAME_WIDTH = 400
GAME_HEIGHT = 800
GAME_DELAY = 100
GAME_BETWEEN_ALIENS = timedelta(seconds=5)
GAME_SUCCESS_COLOR = (0, 255, 0)
GAME_FAILURE_COLOR = (255, 0, 0)
GAME_SUCCESS_TEXT = 'Congrats!'
GAME_FAILURE_TEXT = 'Sorry...'
GAME_MAX_DOWNED_COUNT = 5
GAME_TITLE = f'Сбей {GAME_MAX_DOWNED_COUNT} пришельцев'

BACKGROUND_IMAGE = 'assets/space.png'
BACKGROUND_SPEED = 3

PLAYER_DEFAULT_WIDTH = 50
PLAYER_DEFAULT_HEIGHT = 50
PLAYER_DEFAULT_COLOR = (0, 255, 0)
PLAYER_DEFAULT_SPEED = 5

ALIEN_DEFAULT_SPEED = 5
ALIEN_IMAGES = ['purple', 'golden', 'navy', 'orange', 'brown']
ALIEN_DEFAULT_IMAGE = 'purple'

GAMER_DEFAULT_SPEED = 10
GAMER_DEFAULT_IMAGE = 'soldier'
GAMER_BETWEEN_SHOTS = timedelta(seconds=2)

BULLET_DEFAULT_WIDTH = 4
BULLET_DEFAULT_HEIGHT = 4
BULLET_DEFAULT_COLOR = (255, 0, 0)
BULLET_DEFAULT_SPEED = 10
